name: CI build

on:
  push:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include: 
          - os: ubuntu-18.04
          - os: ubuntu-20.04
          - os: macos-10.15
          - os: macos-11.0
          - os: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - run: git fetch --prune --unshallow
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Build (Linux/mac)
      run: |
        mkdir build
        cd build
        qmake ..
        make -j 2
      if: matrix.os != 'windows-2019'
    - name: Build (Windows)
      run: |
        mkdir build
        cd build
        qmake ..
        nmake
      if: matrix.os == 'windows-2019'
    